version: '3.7'

services:

  compress:
    build: ./
    environment:
     - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
     - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
     - "AWS_REGION=${AWS_S3_REGION}"
     - "AWS_S3_BUCKET=${AWS_S3_BUCKET}"
     - "PUSHER_HOST=${PUSHER_HOST}"
     - "PUSHER_APP_ID=${PUSHER_APP_ID}"
     - "PUSHER_APP_KEY=${PUSHER_APP_KEY}"
     - "PUSHER_APP_SECRET=${PUSHER_APP_SECRET}"
     - "PUSHER_PORT=${PUSHER_PORT}"
     - "PUSHER_CHANNEL=${PUSHER_CHANNEL}"
     - "PUSHER_EVENT=${PUSHER_EVENT}" 

  web:
    image: caddy/caddy:alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "90:80"
    depends_on:
      - compress
  
